apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-data
    namespace: hobbyfarm
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi